### PR TITLE
Add support for generics

### PR DESCRIPTION
**Pull request by JosephLin**
- [x] NSArray
- [x] NSMutableArray
- [x] NSDictionary
- [x] NSMutableDictionary
- [x] NSSet
- [x] NSMutableSet
- [x] NSOrderedSet
- [x] NSMutableOrderedSet

### CODE REVIEW

**Comment by JosephLin** [comment]
related: https://github.com/zwaldowski/BlocksKit/issues/308

**Comment by anayini** [comment]
Hey, I was just working on the exact same thing and saw that you had already got this done.

A couple comments:

- I don't think you need the __covariant in the Category, you can just use the generic type name without it.
- Should you include preprocessor macros that allow this feature based on the availability of generics?  Something like this:
#if __has_feature(objc_generics)
#   define __GENERICS(class, ...)      class<__VA_ARGS__>
#   define __GENERICS_TYPE(type)       type
#else
#   define __GENERICS(class, ...)      class
#   define __GENERICS_TYPE(type)       id
#endif

**Comment by JosephLin** [comment]
@anayini thanks for the suggestions! 
- I've tested it without __covariant and it seems to behave as expected, so I think you're right. But what's the downside of having it? I feel like it makes it a bit more descriptive.

- It's a great idea- I forgot about backward compatibilities :P It requires a lot more changes to the code base, though. Could you create a PR if you already have a working implementation?

**Comment by anayini** [comment]
Sure will do, I think itll just be those preprocessor macros and then changing the interface for each collection to use those macros.  I can probably get to it soon.

Yeah the __covariant stuff could stay in, I guess one could argue that it shouldn't go in the category, because its in the interface of the collection class, but you are right, it doesn't hurt anything.

**Comment by zwaldowski** [comment]
I think I blindly merged the one targeted at the `next` branch, I guess I should merge up that branch. I prefer the approach there as `__covariant` won't be supported on older compilers, which people still find important for some crazy reason. :wink: Points to @JosephLin for getting to it first, though.

**Pull request closed without merging**
